// Copyright 2024 Joe Meszaros
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*
 * Generates `precache-manifest.js`, the list of assets the service worker
 * (`sw.js`) caches on install so the app loads fully offline.
 *
 * This is a no-build app, so the generated file is committed to the repo.
 * Re-run it whenever assets change:  `npm run build:sw`
 *
 * The version string is a content hash of every precached file, so the
 * service worker's cache is busted automatically when any asset changes.
 */

import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, statSync, readdirSync } from 'node:fs';
import { join, relative, sep, posix } from 'node:path';
import { fileURLToPath } from 'node:url';
import { dirname } from 'node:path';

const ROOT = dirname(fileURLToPath(import.meta.url));

// Directories walked recursively. Only files matching `extensions` are included.
const WALK = [
  { dir: 'src', extensions: ['.js', '.json'] }, // app code + i18n translations
  { dir: 'css', extensions: ['.css'] },
  { dir: 'dependencies', extensions: ['.js'] }, // three.js, tabulator, geotiff, laz-perf
  { dir: 'icons', extensions: ['.svg', '.png'] },
  { dir: 'images', extensions: ['.png', '.svg'] }
];

// Explicit individual files (root-level assets fetched at runtime + selected fonts).
const FILES = [
  'index.html',
  'manifest.webmanifest',
  'attributes.json', // fetched by main.js #loadAttributes()
  '.version', // fetched by navbar.js
  'fonts/helvetiker_regular.typeface.json', // three.js 3D text labels
  'fonts/fragmentmono-regular.woff2', // UI @font-face
  'fonts/fragmentmono-regular.woff',
  'fonts/fragmentmono-regular.ttf',
  'fonts/NotoSans-Regular.ttf' // PDF export
  // NOTE: fonts/NotoSansCJKtc-Regular.otf (16 MB) is intentionally excluded
  // from precache; it is runtime-cached on demand by the service worker.
];

function walk(dir, extensions, out) {
  let entries;
  try {
    entries = readdirSync(join(ROOT, dir), { withFileTypes: true });
  } catch {
    return; // directory missing – skip silently
  }
  for (const entry of entries) {
    const rel = join(dir, entry.name);
    if (entry.isDirectory()) {
      walk(rel, extensions, out);
    } else if (extensions.some((ext) => entry.name.endsWith(ext))) {
      out.push(rel);
    }
  }
}

const collected = [];
for (const { dir, extensions } of WALK) walk(dir, extensions, collected);
for (const f of FILES) {
  try {
    statSync(join(ROOT, f));
    collected.push(f);
  } catch {
    console.warn(`[generate-sw] WARNING: listed file not found, skipping: ${f}`);
  }
}

// De-duplicate and use forward-slash URLs (relative, no leading slash so the
// app works whether served from a domain root or a subpath like /speleo-studio/).
const urls = [...new Set(collected.map((p) => p.split(sep).join(posix.sep)))].sort();

// Content hash → cache version. Reading every file keeps the version stable
// across machines (unlike mtimes) and changes the moment any asset changes.
const hash = createHash('sha256');
for (const url of urls) {
  hash.update(url);
  hash.update(readFileSync(join(ROOT, url)));
}
const version = hash.digest('hex').slice(0, 12);

const banner = `// AUTO-GENERATED by generate-sw.js — do not edit by hand.
// Re-run \`npm run build:sw\` after changing assets.
`;
const body =
  `self.__PRECACHE_MANIFEST = ${JSON.stringify({ version, urls }, null, 2)};\n`;

writeFileSync(join(ROOT, 'precache-manifest.js'), banner + body);
console.log(`[generate-sw] wrote precache-manifest.js: ${urls.length} files, version ${version}`);
